/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/Application.java to edit this template
 */
package so.filesystem;

import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JTree;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Aozhen
 */
public class FileSystemApp extends javax.swing.JFrame {
    public FileSystem fs;

    /**
     * Creates new form FileSystemApp
     */
    public FileSystemApp() {
        initComponents();
        
    }
    
    public void test(){
        this.fs = new FileSystem();
        try {
            this.fs.createVD(10, 10);
        } catch (IOException ex) {
            Logger.getLogger(FileSystemApp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void refreshView(){
        DefaultMutableTreeNode root = new DefaultMutableTreeNode(this.fs.getRoot());
        this.fs.getRoot().generateTree(root);
        DefaultTreeModel treeModel = new DefaultTreeModel(root);
        this.jTree1.setModel(treeModel);
        ArrayList<Directory> dirs = this.fs.getCurrent().getDirectories();
        ArrayList<Files> fils = this.fs.getCurrent().getFiles();
        this.jTextField1.setText(this.fs.getCurrent().getRoute());
        DefaultListModel listModel = (DefaultListModel) this.jList1.getModel();
        listModel.removeAllElements();
        for(Directory dir : dirs){
            listModel.addElement(dir);
        }
        for(Files fil : fils){
            listModel.addElement(fil);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dirInputDialog = new javax.swing.JDialog();
        dirTextInput = new javax.swing.JTextField();
        dirInputButtonOk = new javax.swing.JButton();
        dirInputButtonCancel = new javax.swing.JButton();
        fileInputDialog = new javax.swing.JDialog();
        fileNameInput = new javax.swing.JTextField();
        fileButtonOk = new javax.swing.JButton();
        fileButtonCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fileContentInput = new javax.swing.JTextField();
        fileExtensionInput = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        fileOpenDialog = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        fileOpenText = new javax.swing.JTextArea();
        fileOpenBtn = new javax.swing.JButton();
        filePropertiesDialog = new javax.swing.JDialog();
        filePropertiesBtn = new javax.swing.JButton();
        filePropertiesNameText = new javax.swing.JTextField();
        filePropertiesSizeText = new javax.swing.JTextField();
        filePropertiesCreatedText = new javax.swing.JTextField();
        filePropertiesModifiedText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        moveItemDialog = new javax.swing.JDialog();
        moveCurrentPathText = new javax.swing.JTextField();
        moveTargetPathText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        moveBtn = new javax.swing.JButton();
        moveCancelBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        dirInputDialog.setTitle("Input directory name:");
        dirInputDialog.setAlwaysOnTop(true);
        dirInputDialog.setBounds(new java.awt.Rectangle(10, 10, 400, 300));

        dirInputButtonOk.setText("OK");
        dirInputButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dirInputButtonOkActionPerformed(evt);
            }
        });

        dirInputButtonCancel.setText("Cancel");
        dirInputButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dirInputButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dirInputDialogLayout = new javax.swing.GroupLayout(dirInputDialog.getContentPane());
        dirInputDialog.getContentPane().setLayout(dirInputDialogLayout);
        dirInputDialogLayout.setHorizontalGroup(
            dirInputDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dirInputDialogLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(dirInputDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(dirInputDialogLayout.createSequentialGroup()
                        .addComponent(dirInputButtonOk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dirInputButtonCancel))
                    .addComponent(dirTextInput, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        dirInputDialogLayout.setVerticalGroup(
            dirInputDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dirInputDialogLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(dirTextInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dirInputDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dirInputButtonOk)
                    .addComponent(dirInputButtonCancel))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        fileInputDialog.setTitle("Input directory name:");
        fileInputDialog.setAlwaysOnTop(true);
        fileInputDialog.setBounds(new java.awt.Rectangle(10, 10, 400, 300));

        fileButtonOk.setText("OK");
        fileButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileButtonOkActionPerformed(evt);
            }
        });

        fileButtonCancel.setText("Cancel");
        fileButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileButtonCancelActionPerformed(evt);
            }
        });

        jLabel1.setText("Name");

        jLabel2.setText("Content");

        fileContentInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileContentInputActionPerformed(evt);
            }
        });

        fileExtensionInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ".txt", ".docx", ".doc", ".bin" }));

        jLabel3.setText("Extension");

        javax.swing.GroupLayout fileInputDialogLayout = new javax.swing.GroupLayout(fileInputDialog.getContentPane());
        fileInputDialog.getContentPane().setLayout(fileInputDialogLayout);
        fileInputDialogLayout.setHorizontalGroup(
            fileInputDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fileInputDialogLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(fileInputDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(fileInputDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(fileInputDialogLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(fileNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fileInputDialogLayout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(fileButtonCancel)))
                    .addGroup(fileInputDialogLayout.createSequentialGroup()
                        .addGroup(fileInputDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(fileInputDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fileButtonOk)
                            .addComponent(fileContentInput, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fileExtensionInput, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        fileInputDialogLayout.setVerticalGroup(
            fileInputDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fileInputDialogLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(fileInputDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fileInputDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileContentInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fileInputDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileExtensionInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(fileInputDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileButtonOk)
                    .addComponent(fileButtonCancel))
                .addGap(66, 66, 66))
        );

        fileOpenDialog.setBounds(new java.awt.Rectangle(20, 20, 400, 300));

        fileOpenText.setEditable(false);
        fileOpenText.setColumns(20);
        fileOpenText.setRows(5);
        jScrollPane3.setViewportView(fileOpenText);

        fileOpenBtn.setText("OK");
        fileOpenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileOpenBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fileOpenDialogLayout = new javax.swing.GroupLayout(fileOpenDialog.getContentPane());
        fileOpenDialog.getContentPane().setLayout(fileOpenDialogLayout);
        fileOpenDialogLayout.setHorizontalGroup(
            fileOpenDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fileOpenDialogLayout.createSequentialGroup()
                .addGroup(fileOpenDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fileOpenDialogLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(fileOpenBtn))
                    .addGroup(fileOpenDialogLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        fileOpenDialogLayout.setVerticalGroup(
            fileOpenDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fileOpenDialogLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fileOpenBtn)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        filePropertiesDialog.setBounds(new java.awt.Rectangle(10, 10, 400, 300));

        filePropertiesBtn.setText("OK");
        filePropertiesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filePropertiesBtnActionPerformed(evt);
            }
        });

        filePropertiesNameText.setEditable(false);
        filePropertiesNameText.setText("jTextField2");

        filePropertiesSizeText.setEditable(false);
        filePropertiesSizeText.setText("jTextField2");

        filePropertiesCreatedText.setEditable(false);
        filePropertiesCreatedText.setText("jTextField2");

        filePropertiesModifiedText.setEditable(false);
        filePropertiesModifiedText.setText("jTextField2");

        jLabel4.setText("Name");

        jLabel5.setText("Size");

        jLabel6.setText("Created");

        jLabel7.setText("Modified");

        javax.swing.GroupLayout filePropertiesDialogLayout = new javax.swing.GroupLayout(filePropertiesDialog.getContentPane());
        filePropertiesDialog.getContentPane().setLayout(filePropertiesDialogLayout);
        filePropertiesDialogLayout.setHorizontalGroup(
            filePropertiesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filePropertiesDialogLayout.createSequentialGroup()
                .addGroup(filePropertiesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(filePropertiesDialogLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(filePropertiesBtn))
                    .addGroup(filePropertiesDialogLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(filePropertiesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, filePropertiesDialogLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(filePropertiesModifiedText, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, filePropertiesDialogLayout.createSequentialGroup()
                                .addGroup(filePropertiesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(filePropertiesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(filePropertiesSizeText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(filePropertiesNameText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, filePropertiesDialogLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(filePropertiesCreatedText, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        filePropertiesDialogLayout.setVerticalGroup(
            filePropertiesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, filePropertiesDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(filePropertiesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(filePropertiesDialogLayout.createSequentialGroup()
                        .addGroup(filePropertiesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(filePropertiesNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(filePropertiesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(filePropertiesSizeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43))
                    .addGroup(filePropertiesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(filePropertiesCreatedText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(filePropertiesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filePropertiesModifiedText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(filePropertiesBtn)
                .addContainerGap())
        );

        moveItemDialog.setBounds(new java.awt.Rectangle(10, 10, 400, 300));

        moveCurrentPathText.setEditable(false);
        moveCurrentPathText.setText("jTextField2");

        moveTargetPathText.setText("jTextField3");

        jLabel8.setText("Current Path");

        jLabel9.setText("Target Path");

        moveBtn.setText("Move");
        moveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveBtnActionPerformed(evt);
            }
        });

        moveCancelBtn.setText("Cancel");
        moveCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveCancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout moveItemDialogLayout = new javax.swing.GroupLayout(moveItemDialog.getContentPane());
        moveItemDialog.getContentPane().setLayout(moveItemDialogLayout);
        moveItemDialogLayout.setHorizontalGroup(
            moveItemDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moveItemDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(moveItemDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(moveItemDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(moveItemDialogLayout.createSequentialGroup()
                        .addComponent(moveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(moveCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 88, Short.MAX_VALUE))
                    .addComponent(moveTargetPathText)
                    .addComponent(moveCurrentPathText))
                .addContainerGap())
        );
        moveItemDialogLayout.setVerticalGroup(
            moveItemDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moveItemDialogLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(moveItemDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moveCurrentPathText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(50, 50, 50)
                .addGroup(moveItemDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moveTargetPathText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addGroup(moveItemDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moveBtn)
                    .addComponent(moveCancelBtn))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTree1.setCellRenderer(new FileSystemTreeRenderer());
        jTree1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTree1FocusLost(evt);
            }
        });
        jScrollPane2.setViewportView(jTree1);

        jButton1.setText("Open");
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Delete");
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setText("pathTextField");
        jTextField1.setAlignmentX(0.0F);
        jTextField1.setAlignmentY(0.0F);

        jButton3.setText("New File");
        jButton3.setFocusable(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.DefaultListModel()
        );
        jList1.setCellRenderer(new FileSystemListRenderer());
        jList1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jList1FocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jButton4.setText("New Dir");
        jButton4.setFocusable(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Properties");
        jButton5.setFocusable(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Copy");
        jButton6.setFocusable(false);

        jButton7.setText("Move");
        jButton7.setFocusable(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                            .addComponent(jTextField1)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton4)
                        .addComponent(jButton3)
                        .addComponent(jButton5))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dirTextInput.setText("");
        this.dirInputDialog.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void dirInputButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dirInputButtonOkActionPerformed
        // TODO add your handling code here:
        String name = this.dirTextInput.getText();
        this.fs.createDirectory(name);
        this.refreshView();
        this.dirInputDialog.setVisible(false);
        
        
    }//GEN-LAST:event_dirInputButtonOkActionPerformed

    private void dirInputButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dirInputButtonCancelActionPerformed
        // TODO add your handling code here:
        this.dirTextInput.setText("");
        this.dirInputDialog.setVisible(false);
    }//GEN-LAST:event_dirInputButtonCancelActionPerformed

    private void fileButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileButtonOkActionPerformed
        // TODO add your handling code here:
        this.fs.createFile(this.fileNameInput.getText(), this.fileExtensionInput.getSelectedItem().toString(), this.fileContentInput.getText());
        this.fileInputDialog.setVisible(false);
        this.refreshView();
    }//GEN-LAST:event_fileButtonOkActionPerformed

    private void fileButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileButtonCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileButtonCancelActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.fileNameInput.setText("");
        this.fileContentInput.setText("");
        this.fileInputDialog.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void fileContentInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileContentInputActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_fileContentInputActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(this.jList1.isFocusOwner()){
            if(this.jList1.getSelectedValue() instanceof Files file){
                this.fileOpenDialog.setTitle(file.toString());
                this.fileOpenText.setText(file.getContent());
                this.fileOpenDialog.setVisible(true);
            }
            if(this.jList1.getSelectedValue() instanceof Directory dir){
                this.fs.changeMainDir(dir.getName());
                this.refreshView();
            }
        }
        if(this.jTree1.isFocusOwner()){
            if(this.jTree1.getLastSelectedPathComponent() instanceof DefaultMutableTreeNode tNode){
                if(tNode.getUserObject() instanceof Directory dir){
                    this.fs.setCurrent(dir);
                    this.refreshView();
                }
                if(tNode.getUserObject() instanceof Files file){
                    this.fileOpenDialog.setTitle(file.toString());
                    this.fileOpenText.setText(file.getContent());
                    this.fileOpenDialog.setVisible(true);
                }
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void fileOpenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileOpenBtnActionPerformed
        // TODO add your handling code here:
        this.fileOpenDialog.setVisible(false);
    }//GEN-LAST:event_fileOpenBtnActionPerformed

    private void jList1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jList1FocusLost
        // TODO add your handling code here:
        this.jList1.clearSelection();
    }//GEN-LAST:event_jList1FocusLost

    private void jTree1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTree1FocusLost
        // TODO add your handling code here:
        this.jTree1.clearSelection();
    }//GEN-LAST:event_jTree1FocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(this.jList1.getSelectedValue() instanceof Files file){
            this.fs.ReMove(file.getName(), false);
            this.refreshView();
        }
        if(this.jList1.getSelectedValue() instanceof Directory dir){
            this.fs.ReMove(dir.getName(), true);
            this.refreshView();
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if(this.jList1.isFocusOwner()){
            if(this.jList1.getSelectedValue() instanceof Files file){
                LocalDateTime creation = file.getCreation();
                LocalDateTime modification = file.getModification();
                DateTimeFormatter formatC = DateTimeFormatter.ISO_DATE;
                DateTimeFormatter formatM = DateTimeFormatter.ISO_DATE;
                String creationString = creation.format(formatC);
                String modificationString = modification.format(formatM);
                this.filePropertiesDialog.setTitle("Properties of "+file.toString());
                this.filePropertiesNameText.setText(file.toString());
                this.filePropertiesSizeText.setText(Integer.toString(file.getName().length()));
                this.filePropertiesCreatedText.setText(creationString);
                this.filePropertiesModifiedText.setText(modificationString);
                
                this.filePropertiesDialog.setVisible(true);
            }
            if(this.jList1.getSelectedValue() instanceof Directory dir){
                
            }
        }
        if(this.jTree1.isFocusOwner()){
            if(this.jTree1.getLastSelectedPathComponent() instanceof DefaultMutableTreeNode tNode){
                if(tNode.getUserObject() instanceof Directory dir){
                }
                if(tNode.getUserObject() instanceof Files file){
                    LocalDateTime creation = file.getCreation();
                    LocalDateTime modification = file.getModification();
                    DateTimeFormatter formatC = DateTimeFormatter.ISO_DATE;
                    DateTimeFormatter formatM = DateTimeFormatter.ISO_DATE;
                    String creationString = creation.format(formatC);
                    String modificationString = modification.format(formatM);
                    this.filePropertiesDialog.setTitle("Properties of "+file.toString());
                    this.filePropertiesNameText.setText(file.toString());
                    this.filePropertiesSizeText.setText(Integer.toString(file.getName().length()));
                    this.filePropertiesCreatedText.setText(creationString);
                    this.filePropertiesModifiedText.setText(modificationString);
                    this.filePropertiesDialog.setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void filePropertiesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filePropertiesBtnActionPerformed
        // TODO add your handling code here:
        this.filePropertiesDialog.setVisible(false);
    }//GEN-LAST:event_filePropertiesBtnActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if(this.jList1.isFocusOwner()){
            if(this.jList1.getSelectedValue() instanceof Files file){
                this.moveItemDialog.setTitle("Moving File: "+file.toString());
                this.moveCurrentPathText.setText(file.getRoute());
                this.moveTargetPathText.setText(file.getRoute());
                this.moveItemDialog.setVisible(true);
            }
            if(this.jList1.getSelectedValue() instanceof Directory dir){
                this.moveItemDialog.setTitle("Moving Directory: "+dir.toString());
                this.moveCurrentPathText.setText(dir.getRoute());
                this.moveTargetPathText.setText(dir.getRoute());
                this.moveItemDialog.setVisible(true);
            }
        }
        if(this.jTree1.isFocusOwner()){
            if(this.jTree1.getLastSelectedPathComponent() instanceof DefaultMutableTreeNode tNode){
                if(tNode.getUserObject() instanceof Directory dir){
                    this.moveItemDialog.setTitle("Moving Directory: "+dir.toString());
                    this.moveCurrentPathText.setText(dir.getRoute());
                    this.moveTargetPathText.setText(dir.getRoute());
                    this.moveItemDialog.setVisible(true);
                }
                if(tNode.getUserObject() instanceof Files file){
                    this.moveItemDialog.setTitle("Moving File: "+file.toString());
                    this.moveCurrentPathText.setText(file.getRoute());
                    this.moveTargetPathText.setText(file.getRoute());
                    this.moveItemDialog.setVisible(true);
                }
            }
        }
        this.refreshView();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void moveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveBtnActionPerformed
        // TODO add your handling code here:
        this.moveItemDialog.setVisible(false);
        if(this.moveItemDialog.getTitle().contains("Moving Directory")){
            this.fs.Move(this.moveCurrentPathText.getText(), this.moveTargetPathText.getText(), true);
        }
        else{
            this.fs.Move(this.moveCurrentPathText.getText(), this.moveTargetPathText.getText(), false);
        }
        
    }//GEN-LAST:event_moveBtnActionPerformed

    private void moveCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveCancelBtnActionPerformed
        // TODO add your handling code here:
        this.moveItemDialog.setVisible(false);
    }//GEN-LAST:event_moveCancelBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FileSystemApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FileSystemApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FileSystemApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FileSystemApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FileSystemApp fsa = new FileSystemApp();
                fsa.test();
                fsa.refreshView();
                fsa.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dirInputButtonCancel;
    private javax.swing.JButton dirInputButtonOk;
    private javax.swing.JDialog dirInputDialog;
    private javax.swing.JTextField dirTextInput;
    private javax.swing.JButton fileButtonCancel;
    private javax.swing.JButton fileButtonOk;
    private javax.swing.JTextField fileContentInput;
    private javax.swing.JComboBox<String> fileExtensionInput;
    private javax.swing.JDialog fileInputDialog;
    private javax.swing.JTextField fileNameInput;
    private javax.swing.JButton fileOpenBtn;
    private javax.swing.JDialog fileOpenDialog;
    private javax.swing.JTextArea fileOpenText;
    private javax.swing.JButton filePropertiesBtn;
    private javax.swing.JTextField filePropertiesCreatedText;
    private javax.swing.JDialog filePropertiesDialog;
    private javax.swing.JTextField filePropertiesModifiedText;
    private javax.swing.JTextField filePropertiesNameText;
    private javax.swing.JTextField filePropertiesSizeText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<Object> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTree jTree1;
    private javax.swing.JButton moveBtn;
    private javax.swing.JButton moveCancelBtn;
    private javax.swing.JTextField moveCurrentPathText;
    private javax.swing.JDialog moveItemDialog;
    private javax.swing.JTextField moveTargetPathText;
    // End of variables declaration//GEN-END:variables

}
