/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/Application.java to edit this template
 */
package so.filesystem;

import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JTree;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Aozhen
 */
public class FileSystemApp extends javax.swing.JFrame {
    public FileSystem fs;
    private Directory dirTmp;
    private Files fileTmp;
    private VirtualDisc disc;
    private String newDirFile;
    private boolean isDir;
    private Files ifDeleted;
    

    /**
     * Creates new form FileSystemApp
     */
    public FileSystemApp() {
        initComponents();
        
    }
    
    public void test(){
        this.fs = new FileSystem();
    }
    
    public void refreshView(){
        DefaultMutableTreeNode root = new DefaultMutableTreeNode(this.fs.getRoot());
        this.fs.getRoot().generateTree(root);
        DefaultTreeModel treeModel = new DefaultTreeModel(root);
        this.jTree1.setModel(treeModel);
        ArrayList<Directory> dirs = this.fs.getCurrent().getDirectories();
        ArrayList<Files> fils = this.fs.getCurrent().getFiles();
        this.jTextField1.setText(this.fs.getCurrent().getRoute());
        DefaultListModel listModel = (DefaultListModel) this.jList1.getModel();
        listModel.removeAllElements();
        for(Directory dir : dirs){
            listModel.addElement(dir);
        }
        for(Files fil : fils){
            listModel.addElement(fil);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dirInputDialog = new javax.swing.JDialog();
        dirTextInput = new javax.swing.JTextField();
        dirInputButtonOk = new javax.swing.JButton();
        dirInputButtonCancel = new javax.swing.JButton();
        fileInputDialog = new javax.swing.JDialog();
        fileNameInput = new javax.swing.JTextField();
        fileButtonOk = new javax.swing.JButton();
        fileButtonCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fileContentInput = new javax.swing.JTextField();
        fileExtensionInput = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        fileOpenDialog = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        fileOpenText = new javax.swing.JTextArea();
        fileOpenBtn = new javax.swing.JButton();
        filePropertiesDialog = new javax.swing.JDialog();
        filePropertiesBtn = new javax.swing.JButton();
        filePropertiesNameText = new javax.swing.JTextField();
        filePropertiesSizeText = new javax.swing.JTextField();
        filePropertiesCreatedText = new javax.swing.JTextField();
        filePropertiesModifiedText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        moveItemDialog = new javax.swing.JDialog();
        moveCurrentPathText = new javax.swing.JTextField();
        moveTargetPathText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        moveBtn = new javax.swing.JButton();
        moveCancelBtn = new javax.swing.JButton();
        findDialog = new javax.swing.JDialog();
        findTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        findBtnOK = new javax.swing.JButton();
        findBtnCancel = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        findResultsArea = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        modifyDialog = new javax.swing.JDialog();
        jScrollPane5 = new javax.swing.JScrollPane();
        modifyTextArea = new javax.swing.JTextArea();
        modifySaveBtn = new javax.swing.JButton();
        modifyCancelBtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        copyDialog = new javax.swing.JDialog();
        copyAFilePath = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        copyBFilePath = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        copyTypeCombo = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        copyOKBtn = new javax.swing.JButton();
        copyCancelBtn = new javax.swing.JButton();
        setVD = new javax.swing.JDialog();
        textSectors = new javax.swing.JTextField();
        sectorButtonOk = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        textSizes = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        FindDirectory = new javax.swing.JDialog();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        dirInputDialog.setTitle("Input directory name:");
        dirInputDialog.setAlwaysOnTop(true);
        dirInputDialog.setBounds(new java.awt.Rectangle(10, 10, 400, 300));

        dirTextInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dirTextInputActionPerformed(evt);
            }
        });

        dirInputButtonOk.setText("OK");
        dirInputButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dirInputButtonOkActionPerformed(evt);
            }
        });

        dirInputButtonCancel.setText("Cancel");
        dirInputButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dirInputButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dirInputDialogLayout = new javax.swing.GroupLayout(dirInputDialog.getContentPane());
        dirInputDialog.getContentPane().setLayout(dirInputDialogLayout);
        dirInputDialogLayout.setHorizontalGroup(
            dirInputDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dirInputDialogLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(dirInputDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(dirInputDialogLayout.createSequentialGroup()
                        .addComponent(dirInputButtonOk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dirInputButtonCancel))
                    .addComponent(dirTextInput, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        dirInputDialogLayout.setVerticalGroup(
            dirInputDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dirInputDialogLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(dirTextInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dirInputDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dirInputButtonOk)
                    .addComponent(dirInputButtonCancel))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        fileInputDialog.setTitle("Input file name:");
        fileInputDialog.setAlwaysOnTop(true);
        fileInputDialog.setBounds(new java.awt.Rectangle(10, 10, 400, 300));

        fileButtonOk.setText("OK");
        fileButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileButtonOkActionPerformed(evt);
            }
        });

        fileButtonCancel.setText("Cancel");
        fileButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileButtonCancelActionPerformed(evt);
            }
        });

        jLabel1.setText("Name");

        jLabel2.setText("Content");

        fileContentInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileContentInputActionPerformed(evt);
            }
        });

        fileExtensionInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ".txt", ".docx", ".doc", ".bin" }));

        jLabel3.setText("Extension");

        javax.swing.GroupLayout fileInputDialogLayout = new javax.swing.GroupLayout(fileInputDialog.getContentPane());
        fileInputDialog.getContentPane().setLayout(fileInputDialogLayout);
        fileInputDialogLayout.setHorizontalGroup(
            fileInputDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fileInputDialogLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(fileInputDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(fileInputDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(fileInputDialogLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(fileNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fileInputDialogLayout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(fileButtonCancel)))
                    .addGroup(fileInputDialogLayout.createSequentialGroup()
                        .addGroup(fileInputDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(fileInputDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fileButtonOk)
                            .addComponent(fileContentInput, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fileExtensionInput, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        fileInputDialogLayout.setVerticalGroup(
            fileInputDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fileInputDialogLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(fileInputDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fileInputDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileContentInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fileInputDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileExtensionInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(fileInputDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileButtonOk)
                    .addComponent(fileButtonCancel))
                .addGap(66, 66, 66))
        );

        fileOpenDialog.setBounds(new java.awt.Rectangle(20, 20, 400, 300));

        fileOpenText.setEditable(false);
        fileOpenText.setColumns(20);
        fileOpenText.setRows(5);
        jScrollPane3.setViewportView(fileOpenText);

        fileOpenBtn.setText("OK");
        fileOpenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileOpenBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fileOpenDialogLayout = new javax.swing.GroupLayout(fileOpenDialog.getContentPane());
        fileOpenDialog.getContentPane().setLayout(fileOpenDialogLayout);
        fileOpenDialogLayout.setHorizontalGroup(
            fileOpenDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fileOpenDialogLayout.createSequentialGroup()
                .addGroup(fileOpenDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fileOpenDialogLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(fileOpenBtn))
                    .addGroup(fileOpenDialogLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        fileOpenDialogLayout.setVerticalGroup(
            fileOpenDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fileOpenDialogLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fileOpenBtn)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        filePropertiesDialog.setBounds(new java.awt.Rectangle(10, 10, 400, 300));

        filePropertiesBtn.setText("OK");
        filePropertiesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filePropertiesBtnActionPerformed(evt);
            }
        });

        filePropertiesNameText.setEditable(false);
        filePropertiesNameText.setText("jTextField2");

        filePropertiesSizeText.setEditable(false);
        filePropertiesSizeText.setText("jTextField2");

        filePropertiesCreatedText.setEditable(false);
        filePropertiesCreatedText.setText("jTextField2");

        filePropertiesModifiedText.setEditable(false);
        filePropertiesModifiedText.setText("jTextField2");

        jLabel4.setText("Name");

        jLabel5.setText("Size");

        jLabel6.setText("Created");

        jLabel7.setText("Modified");

        javax.swing.GroupLayout filePropertiesDialogLayout = new javax.swing.GroupLayout(filePropertiesDialog.getContentPane());
        filePropertiesDialog.getContentPane().setLayout(filePropertiesDialogLayout);
        filePropertiesDialogLayout.setHorizontalGroup(
            filePropertiesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filePropertiesDialogLayout.createSequentialGroup()
                .addGroup(filePropertiesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(filePropertiesDialogLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(filePropertiesBtn))
                    .addGroup(filePropertiesDialogLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(filePropertiesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, filePropertiesDialogLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(filePropertiesModifiedText, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, filePropertiesDialogLayout.createSequentialGroup()
                                .addGroup(filePropertiesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(filePropertiesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(filePropertiesSizeText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(filePropertiesNameText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, filePropertiesDialogLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(filePropertiesCreatedText, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        filePropertiesDialogLayout.setVerticalGroup(
            filePropertiesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, filePropertiesDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(filePropertiesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(filePropertiesDialogLayout.createSequentialGroup()
                        .addGroup(filePropertiesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(filePropertiesNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(filePropertiesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(filePropertiesSizeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43))
                    .addGroup(filePropertiesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(filePropertiesCreatedText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(filePropertiesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filePropertiesModifiedText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(filePropertiesBtn)
                .addContainerGap())
        );

        moveItemDialog.setBounds(new java.awt.Rectangle(10, 10, 400, 300));

        moveCurrentPathText.setEditable(false);
        moveCurrentPathText.setText("jTextField2");

        moveTargetPathText.setText("jTextField3");

        jLabel8.setText("Current Path");

        jLabel9.setText("Target Path");

        moveBtn.setText("Move");
        moveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveBtnActionPerformed(evt);
            }
        });

        moveCancelBtn.setText("Cancel");
        moveCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveCancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout moveItemDialogLayout = new javax.swing.GroupLayout(moveItemDialog.getContentPane());
        moveItemDialog.getContentPane().setLayout(moveItemDialogLayout);
        moveItemDialogLayout.setHorizontalGroup(
            moveItemDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moveItemDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(moveItemDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(moveItemDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(moveItemDialogLayout.createSequentialGroup()
                        .addComponent(moveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(moveCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 88, Short.MAX_VALUE))
                    .addComponent(moveTargetPathText)
                    .addComponent(moveCurrentPathText))
                .addContainerGap())
        );
        moveItemDialogLayout.setVerticalGroup(
            moveItemDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moveItemDialogLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(moveItemDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moveCurrentPathText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(50, 50, 50)
                .addGroup(moveItemDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moveTargetPathText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addGroup(moveItemDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moveBtn)
                    .addComponent(moveCancelBtn))
                .addContainerGap())
        );

        findDialog.setTitle("Find directory or file routes");
        findDialog.setBounds(new java.awt.Rectangle(10, 10, 400, 400));

        jLabel10.setText("Name");

        findBtnOK.setText("Find");
        findBtnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findBtnOKActionPerformed(evt);
            }
        });

        findBtnCancel.setText("Cancel");
        findBtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findBtnCancelActionPerformed(evt);
            }
        });

        findResultsArea.setEditable(false);
        findResultsArea.setColumns(20);
        findResultsArea.setRows(5);
        jScrollPane4.setViewportView(findResultsArea);

        jLabel11.setText("Results");

        javax.swing.GroupLayout findDialogLayout = new javax.swing.GroupLayout(findDialog.getContentPane());
        findDialog.getContentPane().setLayout(findDialogLayout);
        findDialogLayout.setHorizontalGroup(
            findDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(findDialogLayout.createSequentialGroup()
                .addGroup(findDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(findDialogLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(findDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4)
                            .addGroup(findDialogLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(findTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(findDialogLayout.createSequentialGroup()
                                .addComponent(findBtnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(findBtnCancel))))
                    .addGroup(findDialogLayout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel11)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        findDialogLayout.setVerticalGroup(
            findDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(findDialogLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(findDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(findTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(28, 28, 28)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(findDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(findBtnOK)
                    .addComponent(findBtnCancel))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        modifyDialog.setBounds(new java.awt.Rectangle(10, 10, 400, 300));

        modifyTextArea.setColumns(20);
        modifyTextArea.setRows(5);
        jScrollPane5.setViewportView(modifyTextArea);

        modifySaveBtn.setText("Save");
        modifySaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifySaveBtnActionPerformed(evt);
            }
        });

        modifyCancelBtn.setText("Cancel");
        modifyCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyCancelBtnActionPerformed(evt);
            }
        });

        jLabel12.setText("Contents");

        javax.swing.GroupLayout modifyDialogLayout = new javax.swing.GroupLayout(modifyDialog.getContentPane());
        modifyDialog.getContentPane().setLayout(modifyDialogLayout);
        modifyDialogLayout.setHorizontalGroup(
            modifyDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modifyDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(modifyDialogLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(modifySaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(modifyCancelBtn)
                .addGap(45, 45, 45))
            .addGroup(modifyDialogLayout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        modifyDialogLayout.setVerticalGroup(
            modifyDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modifyDialogLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(modifyDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modifySaveBtn)
                    .addComponent(modifyCancelBtn))
                .addContainerGap())
        );

        copyDialog.setBounds(new java.awt.Rectangle(10, 10, 400, 300));

        copyAFilePath.setEditable(false);
        copyAFilePath.setText("jTextField2");

        jLabel13.setText("Current File Path");

        jLabel14.setText("Copy File Path");

        copyTypeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Real", "Virtual" }));

        jLabel15.setText("Type of Copy");

        copyOKBtn.setText("Copy");
        copyOKBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyOKBtnActionPerformed(evt);
            }
        });

        copyCancelBtn.setText("Cancel");
        copyCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyCancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout copyDialogLayout = new javax.swing.GroupLayout(copyDialog.getContentPane());
        copyDialog.getContentPane().setLayout(copyDialogLayout);
        copyDialogLayout.setHorizontalGroup(
            copyDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, copyDialogLayout.createSequentialGroup()
                .addGroup(copyDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(copyDialogLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, copyDialogLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(copyDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addGroup(copyDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(copyOKBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)))
                .addGroup(copyDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(copyDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(copyTypeCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(copyBFilePath)
                        .addComponent(copyAFilePath, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))
                    .addComponent(copyCancelBtn, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(44, 44, 44))
        );
        copyDialogLayout.setVerticalGroup(
            copyDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(copyDialogLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(copyDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(copyAFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(copyDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(copyBFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(copyDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(copyTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addGroup(copyDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(copyOKBtn)
                    .addComponent(copyCancelBtn))
                .addGap(21, 21, 21))
        );

        setVD.setTitle("Input VD information:");
        setVD.setAlwaysOnTop(true);
        setVD.setBounds(new java.awt.Rectangle(10, 10, 400, 300));
        setVD.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        textSectors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSectorsActionPerformed(evt);
            }
        });

        sectorButtonOk.setText("OK");
        sectorButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sectorButtonOkActionPerformed(evt);
            }
        });

        jLabel16.setText("Number of sectors");

        textSizes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSizesActionPerformed(evt);
            }
        });

        jLabel17.setText("Size of each sector");

        javax.swing.GroupLayout setVDLayout = new javax.swing.GroupLayout(setVD.getContentPane());
        setVD.getContentPane().setLayout(setVDLayout);
        setVDLayout.setHorizontalGroup(
            setVDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setVDLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(setVDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(setVDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(textSizes)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(setVDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(sectorButtonOk, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(textSectors, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        setVDLayout.setVerticalGroup(
            setVDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setVDLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textSectors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textSizes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(sectorButtonOk)
                .addGap(46, 46, 46))
        );

        FindDirectory.setTitle("Directory or file already exists");
        FindDirectory.setAlwaysOnTop(true);
        FindDirectory.setMinimumSize(new java.awt.Dimension(385, 243));

        jButton10.setText("Yes");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("No");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel18.setText("Directory or file you want to add already exists.");

        jLabel19.setText("Do you want to replace it?");

        javax.swing.GroupLayout FindDirectoryLayout = new javax.swing.GroupLayout(FindDirectory.getContentPane());
        FindDirectory.getContentPane().setLayout(FindDirectoryLayout);
        FindDirectoryLayout.setHorizontalGroup(
            FindDirectoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FindDirectoryLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jButton10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton11)
                .addGap(49, 49, 49))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FindDirectoryLayout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(66, 66, 66))
            .addGroup(FindDirectoryLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FindDirectoryLayout.setVerticalGroup(
            FindDirectoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FindDirectoryLayout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addGap(20, 20, 20)
                .addGroup(FindDirectoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10)
                    .addComponent(jButton11))
                .addGap(87, 87, 87))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTree1.setCellRenderer(new FileSystemTreeRenderer());
        jTree1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTree1FocusLost(evt);
            }
        });
        jScrollPane2.setViewportView(jTree1);

        jButton1.setText("Open");
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Delete");
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setText("pathTextField");
        jTextField1.setAlignmentX(0.0F);
        jTextField1.setAlignmentY(0.0F);

        jButton3.setText("New File");
        jButton3.setFocusable(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.DefaultListModel()
        );
        jList1.setCellRenderer(new FileSystemListRenderer());
        jList1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jList1FocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jButton4.setText("New Dir");
        jButton4.setFocusable(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Properties");
        jButton5.setFocusable(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Copy");
        jButton6.setFocusable(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Move");
        jButton7.setFocusable(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Modify");
        jButton8.setFocusable(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Find");
        jButton9.setFocusable(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                            .addComponent(jTextField1)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton4)
                        .addComponent(jButton3)
                        .addComponent(jButton5))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(jButton9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dirTextInput.setText("");
        this.dirInputDialog.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void dirInputButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dirInputButtonOkActionPerformed
        // TODO add your handling code here:
        String name = this.dirTextInput.getText();
        this.newDirFile = name;
        this.isDir = true;
        if(this.fs.createDirectory(name)!=null){
            this.refreshView();
            this.dirInputDialog.setVisible(false);            
        } else{
            this.dirInputDialog.setVisible(false);
            this.fileInputDialog.setVisible(false);
            this.FindDirectory.setVisible(true);
        }
    }//GEN-LAST:event_dirInputButtonOkActionPerformed

    private void dirInputButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dirInputButtonCancelActionPerformed
        // TODO add your handling code here:
        this.dirTextInput.setText("");
        this.dirInputDialog.setVisible(false);
    }//GEN-LAST:event_dirInputButtonCancelActionPerformed

    private void fileButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileButtonOkActionPerformed
        // TODO add your handling code here:
        Files actualF = this.fs.createFile(this.fileNameInput.getText(), this.fileExtensionInput.getSelectedItem().toString(), this.fileContentInput.getText());
        this.isDir = false;
        this.newDirFile = this.fileNameInput.getText();
        //this.ifDeleted = actualF;
        if(actualF != null){
            this.disc.addContent(this.fileContentInput.getText(),actualF);
            this.fileInputDialog.setVisible(false);
            this.refreshView();            
        } else{
            this.FindDirectory.setVisible(true);
        }
    }//GEN-LAST:event_fileButtonOkActionPerformed

    private void fileButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileButtonCancelActionPerformed
        // TODO add your handling code here:
        this.fileInputDialog.setVisible(false);
    }//GEN-LAST:event_fileButtonCancelActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.fileNameInput.setText("");
        this.fileContentInput.setText("");
        this.fileInputDialog.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void fileContentInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileContentInputActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_fileContentInputActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(this.jList1.isFocusOwner()){
            if(this.jList1.getSelectedValue() instanceof Files file){
                this.fileOpenDialog.setTitle(file.toString());
                this.fileOpenText.setText(file.getContent());
                this.fileOpenDialog.setVisible(true);
                this.refreshView();
            }
            if(this.jList1.getSelectedValue() instanceof Directory dir){
                this.fs.changeMainDir(dir.getName());
                this.refreshView();
            }
        }
        if(this.jTree1.isFocusOwner()){
            if(this.jTree1.getLastSelectedPathComponent() instanceof DefaultMutableTreeNode tNode){
                if(tNode.getUserObject() instanceof Directory dir){
                    this.fs.setCurrent(dir);
                    this.refreshView();
                }
                if(tNode.getUserObject() instanceof Files file){
                    this.fileOpenDialog.setTitle(file.toString());
                    this.fileOpenText.setText(file.getContent());
                    this.fileOpenDialog.setVisible(true);
                    this.refreshView();
                }
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void fileOpenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileOpenBtnActionPerformed
        // TODO add your handling code here:
        this.fileOpenDialog.setVisible(false);
    }//GEN-LAST:event_fileOpenBtnActionPerformed

    private void jList1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jList1FocusLost
        // TODO add your handling code here:
        this.jList1.clearSelection();
    }//GEN-LAST:event_jList1FocusLost

    private void jTree1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTree1FocusLost
        // TODO add your handling code here:
        this.jTree1.clearSelection();
    }//GEN-LAST:event_jTree1FocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(this.jList1.getSelectedValue() instanceof Files file){
            this.fs.ReMove(file.getName(), false);
            this.refreshView();
        }
        if(this.jList1.getSelectedValue() instanceof Directory dir){
            this.fs.ReMove(dir.getName(), true);
            this.refreshView();
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if(this.jList1.isFocusOwner()){
            if(this.jList1.getSelectedValue() instanceof Files file){
                LocalDateTime creation = file.getCreation();
                LocalDateTime modification = file.getModification();
                DateTimeFormatter formatC = DateTimeFormatter.ISO_DATE;
                DateTimeFormatter formatM = DateTimeFormatter.ISO_DATE;
                String creationString = creation.format(formatC);
                String modificationString = modification.format(formatM);
                this.filePropertiesDialog.setTitle("Properties of "+file.toString());
                this.filePropertiesNameText.setText(file.toString());
                this.filePropertiesSizeText.setText(Integer.toString(file.getContent().length()));
                this.filePropertiesCreatedText.setText(creationString);
                this.filePropertiesModifiedText.setText(modificationString);
                this.filePropertiesDialog.setVisible(true);
            }
        }
        if(this.jTree1.isFocusOwner()){
            if(this.jTree1.getLastSelectedPathComponent() instanceof DefaultMutableTreeNode tNode){
                if(tNode.getUserObject() instanceof Files file){
                    LocalDateTime creation = file.getCreation();
                    LocalDateTime modification = file.getModification();
                    DateTimeFormatter formatC = DateTimeFormatter.ISO_DATE;
                    DateTimeFormatter formatM = DateTimeFormatter.ISO_DATE;
                    String creationString = creation.format(formatC);
                    String modificationString = modification.format(formatM);
                    this.filePropertiesDialog.setTitle("Properties of "+file.toString());
                    this.filePropertiesNameText.setText(file.toString());
                    this.filePropertiesSizeText.setText(Integer.toString(file.getContent().length()));
                    this.filePropertiesCreatedText.setText(creationString);
                    this.filePropertiesModifiedText.setText(modificationString);
                    this.filePropertiesDialog.setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void filePropertiesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filePropertiesBtnActionPerformed
        // TODO add your handling code here:
        this.filePropertiesDialog.setVisible(false);
    }//GEN-LAST:event_filePropertiesBtnActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if(this.jList1.isFocusOwner()){
            if(this.jList1.getSelectedValue() instanceof Files file){
                this.fileTmp = file;
                this.moveItemDialog.setTitle("Moving File: "+file.toString());
                this.moveCurrentPathText.setText(file.getRoute());
                this.moveTargetPathText.setText(file.getRoute());
                this.moveItemDialog.setVisible(true);
            }
            if(this.jList1.getSelectedValue() instanceof Directory dir){
                this.dirTmp = dir;
                this.moveItemDialog.setTitle("Moving Directory: "+dir.toString());
                this.moveCurrentPathText.setText(dir.getRoute());
                this.moveTargetPathText.setText(dir.getRoute());
                this.moveItemDialog.setVisible(true);
            }
        }
        if(this.jTree1.isFocusOwner()){
            if(this.jTree1.getLastSelectedPathComponent() instanceof DefaultMutableTreeNode tNode){
                if(tNode.getUserObject() instanceof Directory dir){
                    this.dirTmp = dir;
                    this.moveItemDialog.setTitle("Moving Directory: "+dir.toString());
                    this.moveCurrentPathText.setText(dir.getRoute());
                    this.moveTargetPathText.setText(dir.getRoute());
                    this.moveItemDialog.setVisible(true);
                }
                if(tNode.getUserObject() instanceof Files file){
                    this.fileTmp = file;
                    this.moveItemDialog.setTitle("Moving File: "+file.toString());
                    this.moveCurrentPathText.setText(file.getRoute());
                    this.moveTargetPathText.setText(file.getRoute());
                    this.moveItemDialog.setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void moveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveBtnActionPerformed
        // TODO add your handling code here:
        this.moveItemDialog.setVisible(false);
        if(this.moveItemDialog.getTitle().contains("Moving Directory")){
            this.fs.Move(this.moveCurrentPathText.getText(), this.moveTargetPathText.getText(), true);
            this.fs.getCurrent().getDirectories().remove(this.dirTmp);
            this.dirTmp = null;
        }
        else{
            this.fs.Move(this.moveCurrentPathText.getText(), this.moveTargetPathText.getText(), false);
            this.fs.getCurrent().getFiles().remove(this.fileTmp);
            this.fileTmp = null;
        }
        this.refreshView();
    }//GEN-LAST:event_moveBtnActionPerformed

    private void moveCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveCancelBtnActionPerformed
        // TODO add your handling code here:
        this.fileTmp = null;
        this.dirTmp = null;
        this.moveItemDialog.setVisible(false);
    }//GEN-LAST:event_moveCancelBtnActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        this.findDialog.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void findBtnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findBtnOKActionPerformed
        // TODO add your handling code here:
        if(!this.findTextField.getText().isEmpty()){
            this.findResultsArea.setText("");
            for(String s : this.fs.FindRouteList(this.findTextField.getText())){
                this.findResultsArea.append(s+"\n");
            }
        }
    }//GEN-LAST:event_findBtnOKActionPerformed

    private void findBtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findBtnCancelActionPerformed
        // TODO add your handling code here:
        this.findTextField.setText("");
        this.findDialog.setVisible(false);
    }//GEN-LAST:event_findBtnCancelActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        if(this.jList1.isFocusOwner()){
            if(this.jList1.getSelectedValue() instanceof Files file){
                this.modifyTextArea.setText(file.getContent());
                this.modifyDialog.setTitle("Modifying "+file.toString());
                this.fileTmp = file;
                this.modifyDialog.setVisible(true);
            }
        }
        if(this.jTree1.isFocusOwner()){
            if(this.jTree1.getLastSelectedPathComponent() instanceof DefaultMutableTreeNode tNode){
                if(tNode.getUserObject() instanceof Files file){
                    this.modifyTextArea.setText(file.getContent());
                    this.modifyDialog.setTitle("Modifying "+file.toString());
                    this.fileTmp = file;
                    this.modifyDialog.setVisible(true);
                }
            }
        }
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void modifySaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifySaveBtnActionPerformed
        // TODO add your handling code here:
        this.disc.replaceData(this.fileTmp, this.modifyTextArea.getText());
        this.fileTmp = null;
        this.modifyDialog.setVisible(false);
    }//GEN-LAST:event_modifySaveBtnActionPerformed

    private void modifyCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyCancelBtnActionPerformed
        // TODO add your handling code here:
        this.fileTmp = null;
        this.modifyDialog.setVisible(false);
    }//GEN-LAST:event_modifyCancelBtnActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if(this.jList1.isFocusOwner()){
            if(this.jList1.getSelectedValue() instanceof Files file){
                this.modifyDialog.setTitle("Copying "+file.toString());
                this.copyAFilePath.setText(file.getRoute());
                this.copyBFilePath.setText("");
                this.copyDialog.setVisible(true);
            }
        }
        if(this.jTree1.isFocusOwner()){
            if(this.jTree1.getLastSelectedPathComponent() instanceof DefaultMutableTreeNode tNode){
                if(tNode.getUserObject() instanceof Files file){
                    this.modifyDialog.setTitle("Copying "+file.toString());
                    this.copyAFilePath.setText(file.getRoute());
                    this.copyBFilePath.setText("");
                    this.copyDialog.setVisible(true);
                }
            }
        }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void copyOKBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyOKBtnActionPerformed
        // TODO add your handling code here:
        System.out.println(this.copyAFilePath.getText());
        System.out.println(this.copyBFilePath.getText());
        System.out.println(this.copyTypeCombo.getSelectedItem());
        this.copyDialog.setVisible(false);
    }//GEN-LAST:event_copyOKBtnActionPerformed

    private void copyCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyCancelBtnActionPerformed
        // TODO add your handling code here:
        this.copyDialog.setVisible(false);
    }//GEN-LAST:event_copyCancelBtnActionPerformed

    private void sectorButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sectorButtonOkActionPerformed
        // TODO add your handling code here:
        Integer numberSector = Integer.parseInt(this.textSectors.getText());
        Integer sizeSector = Integer.parseInt(this.textSizes.getText());
        try{
            this.disc = new VirtualDisc(numberSector, sizeSector);
        } catch (IOException ex) {
            Logger.getLogger(FileSystemApp.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVD.setVisible(false);
    }//GEN-LAST:event_sectorButtonOkActionPerformed

    private void textSectorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSectorsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSectorsActionPerformed

    private void textSizesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSizesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSizesActionPerformed

    private void dirTextInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dirTextInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dirTextInputActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

        if(this.isDir){
            this.fs.createDirectory(this.newDirFile);
            this.fs.ReMove(this.newDirFile, this.isDir);
        } else{
            Files forDeleted = this.fs.getCurrent().findFile(newDirFile);
            this.disc.deleteFile(forDeleted);
            this.fs.ReMove(this.newDirFile, this.isDir);
            Files actualF = this.fs.createFile(this.fileNameInput.getText(), this.fileExtensionInput.getSelectedItem().toString(), this.fileContentInput.getText());
            this.disc.addContent(this.fileContentInput.getText(),actualF);
        }
        this.refreshView();
        this.FindDirectory.setVisible(false);
        this.dirInputDialog.setVisible(false);
        this.fileInputDialog.setVisible(false);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        this.FindDirectory.setVisible(false);
        this.dirInputDialog.setVisible(false);
    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FileSystemApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FileSystemApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FileSystemApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FileSystemApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FileSystemApp fsa = new FileSystemApp();
                fsa.test();
                fsa.refreshView();
                fsa.setVisible(true);
                fsa.setVD.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog FindDirectory;
    private javax.swing.JTextField copyAFilePath;
    private javax.swing.JTextField copyBFilePath;
    private javax.swing.JButton copyCancelBtn;
    private javax.swing.JDialog copyDialog;
    private javax.swing.JButton copyOKBtn;
    private javax.swing.JComboBox<String> copyTypeCombo;
    private javax.swing.JButton dirInputButtonCancel;
    private javax.swing.JButton dirInputButtonOk;
    private javax.swing.JDialog dirInputDialog;
    private javax.swing.JTextField dirTextInput;
    private javax.swing.JButton fileButtonCancel;
    private javax.swing.JButton fileButtonOk;
    private javax.swing.JTextField fileContentInput;
    private javax.swing.JComboBox<String> fileExtensionInput;
    private javax.swing.JDialog fileInputDialog;
    private javax.swing.JTextField fileNameInput;
    private javax.swing.JButton fileOpenBtn;
    private javax.swing.JDialog fileOpenDialog;
    private javax.swing.JTextArea fileOpenText;
    private javax.swing.JButton filePropertiesBtn;
    private javax.swing.JTextField filePropertiesCreatedText;
    private javax.swing.JDialog filePropertiesDialog;
    private javax.swing.JTextField filePropertiesModifiedText;
    private javax.swing.JTextField filePropertiesNameText;
    private javax.swing.JTextField filePropertiesSizeText;
    private javax.swing.JButton findBtnCancel;
    private javax.swing.JButton findBtnOK;
    private javax.swing.JDialog findDialog;
    private javax.swing.JTextArea findResultsArea;
    private javax.swing.JTextField findTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<Object> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTree jTree1;
    private javax.swing.JButton modifyCancelBtn;
    private javax.swing.JDialog modifyDialog;
    private javax.swing.JButton modifySaveBtn;
    private javax.swing.JTextArea modifyTextArea;
    private javax.swing.JButton moveBtn;
    private javax.swing.JButton moveCancelBtn;
    private javax.swing.JTextField moveCurrentPathText;
    private javax.swing.JDialog moveItemDialog;
    private javax.swing.JTextField moveTargetPathText;
    private javax.swing.JButton sectorButtonOk;
    private javax.swing.JDialog setVD;
    private javax.swing.JTextField textSectors;
    private javax.swing.JTextField textSizes;
    // End of variables declaration//GEN-END:variables

}
